### ISSUE TITLE
基于cpu docker构建工程，运行时出错

### ISSUE THREAD

**Issue by Nicoswang** [OAID/AutoKernel#17]
![image](https://user-images.githubusercontent.com/84898612/119984386-eaab8700-bff3-11eb-8e28-bf89ca08eece.png)

**Comment by lyuchuny3** [comment]
你好，这个问题是tengine库更新引起的，更新后的tengine默认把symbol关了。
目前你可以手动打开：

```
cd /workspace/Tengine/build
 cmake -DTENGINE_ENABLE_ALL_SYMBOL=ON ..
make -j4
make install
```
就能解决问题了

这两天我们会更新docker，把docker里的tengine symbol打开，后两天直接拉docker应该就没问题了
