### ISSUE TITLE
请教当矩阵尺寸过小时如何解决边界索引越界的问题？

### ISSUE THREAD

**Issue by zhen8838** [OAID/AutoKernel#19]
文档中gemm的例子，如果把输入矩阵改成如下：
```cpp
  int M = 20;
  int N = 30;
  int K = 40;
```
那么从step 2开始使用tiling的优化操作的方法都会出现索引越界的问题，可以请教一下应该如何解决吗？
```sh
Aborted
❯ ./06_build.sh 1
step =  1
M N K =  20  30  40     err 0.00        [rep 50] autokernel | blas      0.0112 ms       0.0013 ms
❯ ./06_build.sh 2
step =  2
terminate called after throwing an instance of 'Halide::RuntimeError'
  what():  Error: Input buffer b0 is accessed at 23, which is beyond the max (19) in dimension 1

Aborted
```

**Comment by zhen8838** [comment]
尝试了在生成阶段使用specialize可以进行选择来处理，不过有没有更加好的方法？比如直接边界限制一下？

**Comment by zhen8838** [comment]
再请教一下如何调用specialize后的stage继续进行特化？比如把两个func同步到一个stage？

**Comment by zhen8838** [comment]
发现可以选择tiling的策略来避免这个问题。

最后还有一个疑惑的地方，就是最后的优化策略实际上就是在对K做向量化，但是我尝试直接vectorize(K)这样是不行的，所以才需要用interleave的方式去完成这个事情吗？

**Comment by lyuchuny3** [comment]
不是的，这个例子最后把大矩阵分成小kernel：prod (x=16， y=4), 然后对x维度进行向量化.
对 prod进行 reorder(x,y,k)，要注意这里的变量顺序是从里到外的：
```
for k:
  for y in 4:
     for x in 16;
        vectorize(x,8)
```
interleave的作用使得数据的访存顺序和计算顺序一致，使得计算的时候，需要的数据在cache里，能更快拿到数据。

**Comment by lyuchuny3** [comment]
@zhen8838 , 你可以看下这个：https://github.com/lyuchuny3/Tengine_gemm_tutorial。 这里的interleave和例子里的是一致的
